### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache...DependencyTreeBuilder.buildDependencyTree

### ISSUE THREAD

**Issue by freemant2000** [victims/victims-enforcer#25]
Hi,

I get the error below when I try to run a maven package:

java.lang.NoSuchMethodError: org.apache.maven.shared.dependency.tree.DependencyTreeBuilder.buildDependencyTree(Lorg/apache/maven/project/MavenProject;Lorg/apache/maven/artifact/repository/ArtifactRepository;Lorg/apache/maven/artifact/resolver/filter/ArtifactFilter;)Lorg/apache/maven/shared/dependency/tree/DependencyNode;
    at com.redhat.victims.DependencyTreeCollector.gatherArtifacts(ArtifactCollector.java:103)
    at com.redhat.victims.BaseArtifactCollector.getArtifacts(ArtifactCollector.java:83)
    at com.redhat.victims.VictimsRule.execute(VictimsRule.java:88)
    at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:190)

I am using m2e 1.4.1.20140328-1905.

**Comment by tsujamin** [comment]
Any chance of pushing this out prior to 1.3.5? It's a bit of an issue for us at the moment :)

**Comment by abn** [comment]
@tsujamin I can get a release out next week.

**Comment by ksclarke** [comment]
Any update on when the 1.3.5 release (with this fix) might happen?
