### ISSUE TITLE
Maven 3 incompatibility? NoSuchMethodError for DependencyTreeBuilder.buildDependencyTree

### ISSUE THREAD

**Issue by awood** [victims/victims-enforcer#29]
I'm seeing a strange error with DependencyTreeBuilder.buildDependencyTree(MavenProject project, ArtifactRepository repository, ArtifactFilter filter) which is used in DependencyTreeCollector.  Is this just something local to me?  Have others been successfully using Maven 3 and Victims?

Running the enforcer plugin under Maven 3 (3.1.1-14 from Fedora in my case) results in the below.  The build completes successfully, but no warnings are thrown even when I include a known bad JAR (spring 2.5.6):

```
java.lang.NoSuchMethodError: org.apache.maven.shared.dependency.tree.DependencyTreeBuilder.buildDependencyTree(Lorg/apache/maven/project/Ma
venProject;Lorg/apache/maven/artifact/repository/ArtifactRepository;Lorg/apache/maven/artifact/resolver/filter/ArtifactFilter;)Lorg/apache/
maven/shared/dependency/tree/DependencyNode;
        at com.redhat.victims.DependencyTreeCollector.gatherArtifacts(ArtifactCollector.java:103)
        at com.redhat.victims.BaseArtifactCollector.getArtifacts(ArtifactCollector.java:83)
        at com.redhat.victims.VictimsRule.execute(VictimsRule.java:88)
        at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:190)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by ksclarke** [comment]
This looks, to me, like the same issue as #25 which has been resolved but not yet included in a release.

**Comment by hohwille** [comment]
I am facing the same bug.
Victims has a cool and promising concept but with such bugs it is unfortunately quite useless to me.

**Comment by hohwille** [comment]
All you need to fix is update ```maven-enforcer-plugin```. So this project should update is Readme.md and close this issue.

```
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-enforcer-plugin</artifactId>
            <version>1.4.1</version>
            <dependencies>
              <dependency>
                <groupId>com.redhat.victims</groupId>
                <artifactId>enforce-victims-rule</artifactId>
                <version>1.3.4</version>
                <type>jar</type>
              </dependency>
            </dependencies>
```

**Comment by ashcrow** [comment]
@hohwille thanks for the note. I'll update the README with this. Sorry about the inconvenience.
